# values.yaml
replicaCount: 2

image:
  backend: rybsek/real-back:latest
  frontend: rybsek/real-front:latest

domain: my-realworld-app.com

postgres:
  user: postgres
  db: real_db
  # В продакшене лучше использовать K8s Secrets для пароля!
  password: postgres
