# values.yaml
replicaCount: 2

image:
  backend: rybsek/real-back:latest
  frontend: rybsek/real-front:latest

backend:
  allowedHosts: "35.195.122.18,localhost"

# ... твои образы ...
postgres:
  user: postgres
  password: postgres
  db: real_db
  host: db-service # Имя сервиса внутри K8s
  port: 5432
