name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'deploy']

  push:
    branches: ['master', 'deploy']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  angular_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
    - name: Run tests
      run: npm run test

  django_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        run: python manage.py test
  docker_push:
    runs-on: ubuntu-latest
    needs:
      - django_tests
      - angular_tests
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          targer: prod
          push: true
          tags: rybsek/real-back:latest
      - name: build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          targer: prod
          push: true
          tags: rybsek/real-front:latest
  security:
    needs: docker_push
    runs-on: ubuntu-latest
    steps:
      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'rybsek/real-back:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'rybsek/real-front:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: docker_push

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # 1. Авторизация в Google Cloud
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # 2. Настройка kubectl для твоего кластера
    - name: 'Set up GKE credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: '${{ secrets.CLUSTER_1 }}'
        location: '${{ secrets.CLUSTER_1_ZONE }}' # например, us-central1-c

    # 4. Helm Upgrade
    - name: Deploy with Helm
      run: |
        # Устанавливаем зависимости чарта, если они есть
        helm dependency update ./realworld-chart

        # Запускаем обновление
        helm upgrade --install realworld ./realworld-chart \
          --set postgres.password=${{ secrets.DB_PASSWORD }} \
          --wait --timeout 10m
